### ISSUE TITLE
Resident command doesn't support quiet logging

### ISSUE THREAD

**Issue by Smifferz** [microsoft/p4vfs#23]
I have been doing some testing with P4VFS to investigate how we can utilize it as part of our user syncs. One of the key aspects for us is the ability to re-virtualize any part of a workspace on demand via p4vfs resident -v.

Unlike the sync command, it appears the resident command doesn't support quiet logging? Even after adding the "-q" parameter to the resident command, it presents that it is doing a force|quiet sync but still presents the sync log anyway. (See image below)

![image](https://github.com/microsoft/p4vfs/assets/4955494/c5682153-8644-4ed8-82ac-c4d321f0fc97)

This is not ideal as if we are re-virtualizing an entire workspace, the time taken for this grows exponentially if we don't use quiet logging as the resident command will print every file that has been virtually synced to it's #have revision. This takes a while in a large depot.

**Comment by jessk-msft** [comment]
Hi @Smifferz, 
Thank you for reporting this bug. I've reproduced it exactly as you describe and fixed in 4711694941b58733ad57a0c12222fc9fab91a2b2. We'll include this in the next release. There is a large upcoming change in `dev/reconfig` branch which also affects the `resident` command, but only the hydration `resident -r` option. 
-Jess

**Comment by jessk-msft** [comment]
Fixed in 1.25.1.0
